# Generated by Django 3.2 on 2021-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
