# Generated by Django 3.2 on 2021-09-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='company', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='password',
            field=models.CharField(default='school', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.school'),
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('open', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
