# Generated by Django 3.2 on 2021-09-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210910_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='api.company'),
        ),
    ]
